### ISSUE TITLE
Vocab server options

### ISSUE THREAD

**Issue by rickedanielson** [nansencenter/nersc-metadata#1]
Does reference to the GCMD keywords by [vocabularies on NERC DataGrid](https://marinemetadata.org/references/ndgvocabtable) imply that NERC (via [BODC](http://www.bodc.ac.uk/products/web_services/vocab/) via [SeaDataNet](http://www.seadatanet.org/Standards-Software/Common-Vocabularies)) provides a metadata supserset?

**Comment by mortenwh** [comment]
Thanks! We'll consider this for future use :)
