### ISSUE TITLE
Rename packages

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nersc-metadata#4]
py-metadata-thesaurus
py-metadata-vocabulary

**Comment by akorosov** [comment]
python get vocabulary
python get from vocabulary
python get from thesauri
py-get-metadata-from-voc

**Comment by akorosov** [comment]
py-thesaurus-interface
pythesint
py-vocabulary-interface
pyvocint
py-onomasticon
onomasticon

**Comment by mortenwh** [comment]
Ok, let's go for "py-thesaurus-interface" as repository name with pythesint as short version package name
